### PR TITLE
enable live debugging

### PR DESCRIPTION
**Pull request by humhei**
#7

### CODE REVIEW

**Comment by humhei** [comment]
There is a bug 
After `build` , `bundle.js` will existed in `public` library
In this case, breakpoint will not caught.
So i added ` webpack.config.dev.js ` and  `webpack.config.prod.js`  just as  `create-react-app` done,
the `build` command will output to `"./build"`

**Comment by alfonsogarciacaro** [comment]
Great work @humhei, thanks a lot for this! The template needed some love :wink:

I also took the chance to ["hide" the Webpack config files in the `tools` dir](https://github.com/fable-compiler/fable-templates/commit/70cbff533615a723e6511c079e28a166aad53b20) so they don't scare newcomers. This is a similar though slightly different approach to what we discussed in fable-scripts. Could you (and maybe also @MangelMaxime @whitetigle) have a look and tell me what you think before publishing a new version of the template?

Please have a look at the README to see the changes (the last section "Project Structure" hasn't really changed so you can skip it).

- I'm only using `yarn` to make things simpler for users
- yarn calls automatically `dotnet restore`
- Fable (and other CLI tools if necessary) are also moved to `tools` dir and called automatically by `yarn start/build`
- To avoid the need to worry about webpack config files I've moved Fable config details (for now, only the entry file) to a `fable` section in package.json.
- I haven't added SASS compilation to the template yet, maybe we should do it to share configuration with the Fulma template?

**Comment by MangelMaxime** [comment]
Personally, I think by doing this we just delay the moment when users will need to underscore paket, yarn, webpack, etc.

But for the simple template, it make sense so I am ok with that.

**Comment by humhei** [comment]
I tried to run task 
but interruped with below message
`Executing task: C:\Program Files (x86)\Yarn\bin\yarn start <`

**Comment by alfonsogarciacaro** [comment]
@humhei Do you have `yarn` installed? Does it change if you replace `yarn` with `npm` in [this line](https://github.com/fable-compiler/fable-templates/blob/70cbff533615a723e6511c079e28a166aad53b20/simple/Content/.vscode/tasks.json#L5)?

@MangelMaxime Yes, for that we still need the tutorial series :wink: But for the template I think most of users want to start as soon as possible and many get confused if there are extra "unusual" steps (I was helping a user yesterday and after trying several things the problem was they were not running `dotnet fable` from `src` dir).

**Comment by humhei** [comment]
three suggestions
* How about place `index.html` in `public` dir just as `create-react-app` done?
 I Think this is more common
* Update `tasks.json` to version 2.0. As it get worked for me
```shell
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "command": "yarn",
            "args": ["start"],
            "type": "shell",
            "label": "Start",
            "group": "build",
            "isBackground": true,
            "problemMatcher": {
                "fileLocation": "absolute",
                "background": {
                    "activeOnStart": true,
                    "beginsPattern":{
                        "regexp": "webpack: Compiling"
                    },
                    "endsPattern":{
                        "regexp": "webpack: (Compiled successfully|Failed to compile)"
                    }
                },
                "pattern": {
                    "regexp": "^(.*)\\((\\d+),(\\d+)\\): \\((\\d+),(\\d+)\\) (warning|error) FABLE: (.*)$",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "endLine": 4,
                    "endColumn": 5,
                    "severity": 6,
                    "message": 7
                }
            }
        }
    ]
}
```
* Use FAKE CLI by default and place `fsx` files in` tools` dir
```
    "build": "cd tools && dotnet fable webpack -- -p --config webpack.config.prod.js",
    "start": "cd tools && dotnet fable webpack-dev-server -- --config webpack.config.dev.js",
```
Above code is bad to read
I  more like seeing below scripts
```
    "build": "fake run tools/build.fsx",
    "start": "fake run tools/start.fsx",
```

**Comment by humhei** [comment]
I also took a chance to add FAKE in workflow https://github.com/fable-compiler/fable-templates/pull/9
It works well for me besides the console color is all the yellow

**Comment by humhei** [comment]
The last commit fixed the **yellow** output,
Currently webpack output color will be normal

**Comment by alfonsogarciacaro** [comment]
Thanks for the tip about VS Code tasks version @humhei! [I upgraded it](https://github.com/fable-compiler/fable-templates/commit/f8bf1cc7229fe6739aa71144534b483c6db3ad88). I saw you closes your PR, are you planning to send it again? Adding FAKE to the basic template is a bit controversial, and has been discussed some times before. In principle, I'd like to avoid it because it's not strictly necessary and it adds some cognitive overhead specially to users coming from JS, who already need to learn about F#, dotnet SDK, Paket...

Should we publish the template as it is now so users an give feedback?

**Comment by humhei** [comment]
I feel the same

**Pull request merged**
