### PR TITLE
Adds new Fable template which uses Snowpack instead of Webpack

### PR DESCRIPTION
**Pull request by mabasic**
Inspired by: https://www.youtube.com/watch?v=yqOWx-6FXAs

In the video he shows an example running React.js, but for this template I've used the same example as is in the minimal template.

### CODE REVIEW

**Comment by MangelMaxime** [comment]
When running it from a fresh clone, I have an error:

image

**Comment by mabasic** [comment]
That is to expect because those files are not included in the template. They are generated on first run. If you open the page in the browser you will see that they are loaded correctly once F# code compiles.

**Comment by MangelMaxime** [comment]
Ok, I retried and I don't know why it is working now.

Before, the app was doing nothing :man_shrugging: 

Because, I can't push to your fork, I rebased the changes directly into master.

I still don't understand why I can't push to fork based on fable-compiler org when I am owner of it :man_shrugging: 

Thank you for the PR

**Comment by mabasic** [comment]
Glad to be able to contribute. I think that there is a way to contribute to my fork, but it has some steps...

**Comment by MangelMaxime** [comment]
In theory they made it transparent if you have checked the "Allow maintainer to push" in the PR.

And it works well in general, for example in Nacara I am able to do it and a lot of others places too. Just not under the fable-org organization... (I kind of just accepted that fact now, even it is not really nice)

**Pull request closed without merging**
