### PR TITLE
Updated to paket 5.100.2, fixes issue with dotnetstandard 2

### PR DESCRIPTION
**Pull request by BenHewins**
I think it's the same as described here:
https://github.com/fsprojects/Paket/issues/2680

### CODE REVIEW

**Comment by forki** [comment]
What is this change about? Updating the bootstrapper?

**Comment by BenHewins** [comment]
Sorry, yes, it changes paket.exe to the latest paket.bootstrapper.exe from here:
https://github.com/fsprojects/Paket/releases/tag/5.100.2

**Comment by forki** [comment]
@alfonsogarciacaro @MangelMaxime can you please release it?

**Comment by alfonsogarciacaro** [comment]
Fable.Template 1.2.5 pushed from Bordeaux HQ :)

**Comment by forki** [comment]
Hugs

Am 23.09.2017 14:54 schrieb "Alfonso Garcia-Caro" <notifications@github.com

**Pull request merged**
